### ISSUE TITLE
Security patch - Axios vulnerability

### ISSUE THREAD

**Issue by petruki** [switcherapi/switcher-api#83]
- [x] Introduced through: switcher-api@switcherapi/switcher-api#8d9458bf93d280ee311a975a46c2e1f2c69dd982 › @sendgrid/mail@7.4.0 › @sendgrid/client@7.4.0 › axios@0.19.2
- [x] Introduced through: switcher-api@switcherapi/switcher-api#8d9458bf93d280ee311a975a46c2e1f2c69dd982 › axios@0.20.0
- [x] Introduced through: switcher-api@switcherapi/switcher-api#8d9458bf93d280ee311a975a46c2e1f2c69dd982 › switcher-client@2.0.8 › axios@0.20.0

**Comment by petruki** [comment]
SendGrid client must be fixed. It's still using an older version of axios.
